# docker-compose.yml
version: '3.5'

services:

  # Services
  consignment:
    restart: always
    build: ./shippy-service-consignment
    image: shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  # Commands
  cli:
    build: ./shippy-cli-consignment

  # Database tier
  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - data:/data/db # ensures data persistence between restarting
    ports:
      - 27017
    command: mongod --logpath=/dev/null

  user:
    build: ./shippy-service-user
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "database"
      DB_USER: "admin"
      DB_NAME: "postgres"
      DB_PASSWORD: "password"


  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432

  user-cli:
    build: ./shippy-cli-user

  api:
    image: micro/micro:v2.9.3
    ports:
      - 8080:8080
    environment:
      MICRO_REGISTRY: "mdns"
    command: api --handler=rpc --address=:8080 --namespace=shippy --enable_rpc=true  --resolver=grpc

volumes: 
  data: